services:
  - type: web
    name: chitchat
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://chitchat.onrender.com
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
      - key: NODE_ENV
        value: production
